version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: node.dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
      - "22:22"
